### ISSUE TITLE
Can't run Pleco

### ISSUE THREAD

**Issue by Melvillian** [sfleischman105/Pleco#38]
I try to run the pleco binary, but nothing happens. Ever since this commit

https://github.com/sfleischman105/Pleco/commit/57250eff05bbd793a5b95772098bcadb0c2cb0f2

the `main.rs` function has been empty. How am I supposed to run this?

**Comment by sfleischman105** [comment]
Hi @Melvillian,

Some of the branches got mixed up when pushing. This'll be fixed soon.

**Comment by sfleischman105** [comment]
Fixed with #40 

Right now pleco.rs is only available for use with a UCI interface, or for usage as an external library for implementing chess into your own program. In the future we'll be adding more commands for other uses.
